font_name: icons
css_selector: .icon-{{glyph}}
preprocessor_path: false
autowidth: false
no_hash: true
force: false
debug: false
quiet: false

input:
  vectors: app/assets/fonts/icons
  templates: app/assets/fonts/icons

output:
  fonts: app/assets/fonts
  css: app/assets/stylesheets/icons/
  preview: app/assets/fonts/styleguide

templates: ['scss-rails', 'preview']
