application:
  name: 'Billet'
  logo_text: 'Billet'
admin:
  name: <%= ENV.fetch('APP_SETTINGS_OWNER_LOGIN', 'admin') %>
  password: <%= ENV.fetch('APP_SETTINGS_OWNER_PASSWORD', 'epyfnm3epyfnm') %>

unconfirmed_days: 3

links:
  facebook: 'https://www.facebook.com/billet'
  twitter: 'https://twitter.com/billet'
  support: 'mailto:support@billet.com'

default_user_config:
  date_format: '%d/%m/%Y'
  full_date_format: '%d/%m/%Y %H:%I'
  percentage_format: "%n %"

providers:
  github:
    key: <%= ENV.fetch('GITHUB_ID', nil) %>
    secret: <%= ENV.fetch('GITHUB_SECRET', nil) %>
  facebook:
    key: <%= ENV.fetch('FACEBOOK_ID', nil) %>
    secret: <%= ENV.fetch('FACEBOOK_SECRET', nil) %>
